spring.datasource.url=jdbc:postgresql://PROD_HOST:5432/banking_user_account
spring.datasource.username=prod_user
spring.datasource.password=prod_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
